### ISSUE TITLE
Strange incompatability

### ISSUE THREAD

**Issue by NoobChester** [PhiPro95/mc-fixes#2]
Crash log: https://paste.ee/p/5edGn
Log: https://paste.ee/p/nWzdE

Modlist:
1. https://github.com/PhiPro95/mc-fixes/releases/tag/lighting-fixes-v1.0.0
2. https://github.com/gudenau/minecraft-gudfps/releases/tag/v0.0.2
3. https://github.com/jellysquid3/phosphor-fabric/releases/tag/mc1.16.1-v0.6.0

Curseforge links for phosphor and gudFPS:
https://www.curseforge.com/minecraft/mc-mods/gudfps/files/3030046
https://www.curseforge.com/minecraft/mc-mods/phosphor/files/2987621

The crash only occurs when those three mods are all loaded, combinations like "1. 3." , "1. 2." , "2. 3." are fine.

**Comment by NoobChester** [comment]
https://github.com/jellysquid3/phosphor-fabric/issues/13#issuecomment-675417676
Someone told me this is due to phosphor and lighting-fixes being incompatible, gudFPS just makes it crash on launch.
I will close this issue now, sorry to bother.

**Comment by PhiProven** [comment]
We are working on a fix for the compatibility issue. The current plan is to include my code into Phosphor, but we don't have any ETA for that.

**Comment by fdgonzalez781** [comment]
With some brute force refactoring I was able to get custom builds of Phosphor and mc-fixes to launch together on Minecraft 1.16.1. I'm not sure if it really makes sense to include it as a pull request, especially if you're going to incorporate the fixes into Phosphor (and because I had to patch both mods), but I'll include the forks for people who want to use the mods together, at least as a temporary fix.

My only goal was compatibility, so I just preserved the original logic of both mods and tried to split them into smaller/less invasive mixins when I could. Ideally, the mods' behaviors and performance should be identical to their official counterparts. Phosphor for Minecraft 1.16.2 is not out yet, so I downgraded mc-fixes to work with Minecraft 1.16.1.

I'm not completely sure if the resulting lighting logic makes sense, but the game launches, no unexpected errors, performance seems to be good, and I haven't yet seen any new issues or glitches apart from maybe issue PhiPro95/mc-fixes#1. Also, not sure if there would be compatibility issues anyway, but these custom builds of Phosphor and mc-fixes work with Sodium and Lithium as well, without any modifications necessary for Sodium or Lithium.

I was mainly inspired to work on this because not being able to use mc-fixes with Sodium/Lithium/Phosphor (and having huge lag spikes when crossing some chunk borders...) was *incredibly* painful, so thank you for creating these fixes in the first place. :)

mc-fixes: https://github.com/the6thdoor/mc-fixes
Phosphor: https://github.com/the6thdoor/phosphor-fabric

**Comment by PhiProven** [comment]
Hi @the6thdoor . Feel free to join JellySquid's discord, which can be found on her Github repos, in case you want (and have time to) assist in porting the code 😃 

I hope my frequent force-pushes to `lighting-fixes` arent't too annoying :P That branch was primarily intended for personal use and I didn't have time yet to polish the setup, mainly due to some annoying Mixin and Loom bugs.

**Comment by DragonEggBedrockBreaking** [comment]
> Phosphor for Minecraft 1.16.2 is not out yet, so I downgraded mc-fixes to work with Minecraft 1.16.1.
> 
> mc-fixes: https://github.com/the6thdoor/mc-fixes
> Phosphor: https://github.com/the6thdoor/phosphor-fabric

Would you mind updating your forks to make mc-fixes work with the newest phosphor version? I understand if it is too difficult/you don't have the time.

**Comment by fdgonzalez781** [comment]
Fortunately, I believe as of Phosphor 0.7, mc-fixes has been merged into Phosphor, so my forks shouldn't be necessary anymore.

**Comment by DragonEggBedrockBreaking** [comment]
> Fortunately, I believe as of Phosphor 0.7, mc-fixes has been merged into Phosphor, so my forks shouldn't be necessary anymore.

Ah, OK, cool!
